services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
      # The above will create a directory called mongo_data to your local filesystem and map it into the container as /data/db
  # volumes:
  #   mongo_data:
  # Now the volume is created and managed by Docker. After starting the application:
  # docker compose -f docker-compose.dev.yml up
  # you can list the volumes with:
  #  docker volume ls
  # inspect one of them with:
  # docker volume inspect
  #  and even delete them with:
  # docker volume rm
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
